Feat: add navbar & footer
jeriken/hmpsweb pull request #4
Opened 2020-09-27 09:06 UTC by nawwab

adding navbar, footer, and vue-router in it:

step for adding a new page:
- create new component in resources/js/views
- add and edit the router.js
- add the router-link in navbar & footer in index.vue

notes: please use class below in page wrapper/div (for spacing)
`class="max-w-screen-lg mx-auto px-4 sm:px-6 py-6 sm:py-12 ..."`

2020-09-27 11:49 UTC, ahmaddynugroho requested changes
## Problem: 
1. Style `resources/js/app.js` line 2-3 tidak sama dengan `resources/js/router.js` line 3
2. `resources/js/router.js` line 3 adalah import static yang berarti component akan selalu di-load walaupun tidak dipakai

## Solution:
1. Tolong ikutsertakan ekstensi untuk import yang bukan module npm
`import App from './index.vue'`
`import router from './router.js'`

2. Ganti menjadi `const home = () => import('./views/Home.vue')`, maka component akan di-load ketika dipakai saja

#### Note:
1. Karena solusi nomer 2 adalah menggunakan variable, maka pemberian nama menggunakan camelCase

#### Ref:
1. https://medium.com/javascript-in-plain-english/javascript-naming-convention-best-practices-b2065694b7d
2. https://router.vuejs.org/guide/advanced/lazy-loading.html

2020-09-27 12:09 UTC, ahmaddynugroho reviewed
1. `resources/js/views/Home.vue` nggak dikasih `class="max-w-screen-lg mx-auto px-4 sm:px-6 py-6 sm:py-12 ..."` ?
2. titik tiga itu maksudnya gimana? `class="max-w-screen-lg mx-auto px-4 sm:px-6 py-6 sm:py-12 ..."`

2020-09-27 13:13 UTC, nawwab commented
aku kayaknya yang salah deh:
1. ok aku benerin
2. itu maksudnya class yang lain yang contributor lain mau tambahin, tapi bakal kuhapus biar ngga pusing

2020-09-30 06:17 UTC, merged

2020-10-01 07:14 UTC, nawwab commented
Thanks!